// import { init } from './js/crearHTML';
// import { init } from './js/usuarios-page';
// import * as CRUD from './js/CRUD-provider';
import {init} from './js/archivos-page';
// CRUD.getUser(1).then(console.log);
// CRUD.crearUser({name:'Brayan Gonzalez', job:'Developer'}).then(console.log);
// CRUD.actualizarUser(2, {name:"Brayan Gonzalez", job:"Developer"}).then(console.log);
// CRUD.borrarUser(2).then(console.log);
// init();
init();